### ISSUE TITLE
Deletion of interior faces

### ISSUE THREAD

**Issue by anaanook** [QodotPlugin/Qodot#100]
Meshes built by Qodot does not prune interior/non visible faces that are normally pruned by the BSP build process.  

This especially leads to immense amounts of wasted texture space when lightmaps are generated.

**Comment by RhapsodyInGeek** [comment]
Qodot is not a BSP compiler and will not do this automatically for you. Instead you need to make use of the Clip and Skip textures to better optimize your map. Please read the [**Qodot Tutorial**](https://github.com/RhapsodyInGeek/Qodot-Entity-Tutorial/) for more information.
