### ISSUE TITLE
Preferred map format option for game definition

### ISSUE THREAD

**Issue by Braboware** [QodotPlugin/Qodot#102]
With the current game definition generation, "Standard" appears as the default map format in trenchbroom. It would be nice for quality of life to be able to choose which map format appears at the top of the list. Sometimes I forget to choose "Valve" format and have to copy the brushes to a new map file in valve format so I can use the nicer texture alignment features.

Currently I am just manually editing the `fileformats` order in the cfg to make the "Valve" format first

**Comment by RhapsodyInGeek** [comment]
I'll look into it when I have time, though I'm busy with a few big personal projects atm. It is something that'd I'd like to have added though, and shouldn't be too difficult to add.

I'm thinking it'd probably be an Array[String] type, with the default being the default map formats. In the resource inspector you can reorder Arrays by dragging, so you wouldn't even need to type them in. IIRC TrenchBroom Game Configs also don't need to have every map format listed, so you should be able to remove all but the ones you want, too.
