### ISSUE TITLE
Replace qodot with a .map to gltf compiler?

### ISSUE THREAD

**Issue by andyjh92** [QodotPlugin/Qodot#103]
Wouldn't it be a better to compile .map files to gltf than qodots approach? Then every game engine can use the map, not only godot.
https://github.com/fLindahl/map-to-gltf is an example

**Comment by RhapsodyInGeek** [comment]
Godot itself doesn't actually read GLTFs directly IIRC, it instead generates MeshInstance3Ds, materials, animations, etc... based upon the GLTF specification (similar to how Qodot builds map files). This is also outside of Qodot's scope as it does a lot more than just build map meshes and collision.

If you want a GLTF version of the built QodotMap, you can already do so with Godot's built-in "Export Scene to GLTF" feature if you actually want to use it in other engines.
