### ISSUE TITLE
Quick Build/Full Build/Unwrap do not appear on top bar for Qodot node

### ISSUE THREAD

**Issue by Xiphozuran** [QodotPlugin/Qodot#105]
Hello, new to github, new to Godot/Qodot. Was just having an issue with Qodot, it seems the three options mentioned in the post title will not appear even with a Qodot Map node in use. Any help would be appreciated. Thanks!

**Comment by RhapsodyInGeek** [comment]
Did you enable the plugin in your project settings? Did you build the C# project? Do you have the QodotMap node selected?

**Comment by Xiphozuran** [comment]
The plugin is enabled and I do have the map node selected. I'm not sure what you mean by "build the C# project", however.

**Comment by Xiphozuran** [comment]
nvm figured it out
