### ISSUE TITLE
Parent signature not matching at _import on quake_wad_import_plugin.gd

### ISSUE THREAD

**Issue by jmarceno** [QodotPlugin/Qodot#107]
Godot Version. 4.1.3.stable
Qodot Version: d5fa9e7

I´m testing the new GDScript implementation and Godot was throwing an error on _import from quake_wad_import_plugin.gd.
I believe it is because I have some type checks on, which prevents the plugin from properly initializing on type mismatch.

Changing it from:
`func _import(source_file, save_path, options, r_platform_variants, r_gen_files) -> int:`
to:
`func _import(source_file, save_path, options, r_platform_variants, r_gen_files) -> Error:`

Has fixed the problem and I´m able to generate the map.

**Comment by EMBYRDEV** [comment]
Should be fixed as of https://github.com/QodotPlugin/Qodot/commit/7bf6212ea2ee3160c19c5d7b6f6b42297a5e0864
