### ISSUE TITLE
Extreme fps drop when walking into column corner

### ISSUE THREAD

**Issue by 111raigeki** [QodotPlugin/Qodot#108]
Hello,

I created a number of 12-sided columns in trenchbroom and the fps takes a massive hit when I am walking into the corner of these columns. It also happens if I walk into the face of a column, but not this drastic.

Video example: https://youtu.be/X0MBwr4ZbCs

**Settings in video example:**
- FPS capped @ 400
- V-sync disabled
- 800x600 windowed
- Forward+

**Sofware:**
- Linux Mint 21.2
- Godot 4.1.3 Mono
- TrenchBroom 2023.1

I'm very new to this and probably doing something wrong, so please excuse me if there is an obvious mistake on my side.

**Comment by EMBYRDEV** [comment]
This seems like an issue with the Godot physics engine, does the Jolt extension help?
