### ISSUE TITLE
make QodotMap more friendly to version control (?)

### ISSUE THREAD

**Issue by k4gi** [QodotPlugin/Qodot#110]
Hello,

whenever i do a Full Build of a new version of my map, it seems that the unique IDs for the resources QodotMap makes are changing. for example:

`[sub_resource type="StandardMaterial3D" id="StandardMaterial3D_oa3bv"]`

changing to

`[sub_resource type="StandardMaterial3D" id="StandardMaterial3D_jbr82"]`

this is adding a lot of meaningless noise to my git history, which, i don't know if it's a _problem_, but it's unnecessary.

perhaps if there was a button alongside Build and Unwrap that deleted all the children? idk

thanks

**Comment by EMBYRDEV** [comment]
It's a sub resource generated by the QodotMap fresh every time you build. If you use hand made materials stored in your project hierarchy instead of relying on imagees or the WAD file then this shouldn't happen.
