### ISSUE TITLE
Visuals not set to build by default in the latest version

### ISSUE THREAD

**Issue by JillCrungus** [QodotPlugin/Qodot#112]
Even in a fresh project using the example scenes, any attempt to build the map won't create a MeshInstance3D at all. Quick build does nothing except for making the map bounds visible when selected and full build will successfully generate an occluder and collision shapes but still produces no mesh.

This seems to be because the [latest commit](https://github.com/QodotPlugin/Qodot/commit/2df08b88840ce9a35a1c157ad8693e8dd5c6442e#diff-1b6de8ec866de365fd83476cdda59827a750f415325fbea6d58f826c9d6bcf32) changed `addons/qodot/game_definitions/fgd/solid_classes/worldspawn_solid_class` to have "Build Visuals" disabled by default. Re-enabling this fixes the issue. I assume that this is an unintentional change that should be reverted since it means that Qodot's core functionality appears broken out of the box.

**Comment by EMBYRDEV** [comment]
Lmao, I'm a dumbass, thanks for the report.
