### ISSUE TITLE
FGD bug make choices without description give an error in TB.

### ISSUE THREAD

**Issue by PPBoxHead** [QodotPlugin/Qodot#115]
When creating choices for the custom entities if they don't have any description they make a issue on TrenchBroom were it doesn't read right the fgd.
Here are some choices without a description done:
![image](https://github.com/QodotPlugin/Qodot/assets/89146265/67473ec6-6b88-4fef-a789-76adf3e350b1)

And this is the error result in TrenchBroom and the FGD file code line is pointing at:
![image](https://github.com/QodotPlugin/Qodot/assets/89146265/2a1d9a6c-cfb5-488a-877d-f4fe47b34e27)
FGD:
![image](https://github.com/QodotPlugin/Qodot/assets/89146265/2b8cebdf-043e-47c4-96c5-abc47fb4e323)

**Comment by RhapsodyInGeek** [comment]
Issue should be resolved now.
