### ISSUE TITLE
Setting FGD type of files both on entities and in FGDFile resources gives different kind of errors in TrenchBroom

### ISSUE THREAD

**Issue by PPBoxHead** [QodotPlugin/Qodot#122]
When you put a FGDFile resource in the Base FGD Files array on another FGDFile resource
![image](https://github.com/QodotPlugin/Qodot/assets/89146265/181c1068-bf0c-4640-9dfa-4f35364627b5)

This is the error given in TrenchBroom:
![image](https://github.com/QodotPlugin/Qodot/assets/89146265/3f005b4e-b5a4-4b35-a43f-03e32c70edac)

Also, when you add a base FGDClass on the Base Classes array of both Point or Solid entity types like here:
![image](https://github.com/QodotPlugin/Qodot/assets/89146265/e264848e-0f27-42cb-bd03-1731f9ca6e50)

You will receive this error on TrenchBroom:
![image](https://github.com/QodotPlugin/Qodot/assets/89146265/363d27ff-6db0-4038-9f71-f8800dafee07)

**Comment by RhapsodyInGeek** [comment]
This setup exports just fine, using any number of Base FGD files, exporting it from GameConfig or from the FGD File resource.
![image](https://github.com/QodotPlugin/Qodot/assets/44485952/ea458dac-3f20-4de2-af0c-738adae27672)

My best guess is there's something wrong with your door_systems FGD File resource.

And this setup with multiple base classes works as well.
![image](https://github.com/QodotPlugin/Qodot/assets/44485952/91e337c3-9525-4ebf-ae04-640d8392eaf5)

Did you make sure to include your targetname and target base classes in your FGD File Resource? They need to be included in that along with all of your other entity classes.

**Comment by PPBoxHead** [comment]
with the include you mean having it on the Class Properties of the DoorSolid itself?

**Comment by RhapsodyInGeek** [comment]
That's where you've got it wrong. The base classes don't belong in the Base FGD Files array. They belong in the Entity Definitions array. Base FGD Files are for the QodotFGDFiles only.

**Comment by PPBoxHead** [comment]
Btw, the screenshot with the target thing in fact is not from the door system entities, is from the Receiver and also the Signal entities built-in the qodot addon folder

**Comment by PPBoxHead** [comment]
Alright, the Base FGD Files array problem is fixed, now I'm still having the Base Classes error given in TrenchBroom about Target and Targetname, anyways setting targetname and target on entities works right, this error might not let me make other Base Classes in the future (still needing to test it)

**Comment by RhapsodyInGeek** [comment]
This error is caused by the Target and Targetname base classes being undefined in your FGD file.
![image](https://github.com/QodotPlugin/Qodot/assets/44485952/f77068ec-4d96-488d-806a-4123b2f40035)

This usually happens if you either forget to include the base class resource in the correct location (which is what your screenshot of your `door_systems.tres` shows) or that you didn't provide your base classes with a `Classname`.

**Comment by RhapsodyInGeek** [comment]
Can you share your FGD file output?

**Comment by PPBoxHead** [comment]
Sorry the delay, what do you mean with FGD file output?

**Comment by PPBoxHead** [comment]
This one?
![image](https://github.com/QodotPlugin/Qodot/assets/89146265/0a58d065-f02f-4958-814b-259494d76804)

**Comment by RhapsodyInGeek** [comment]
No, I meant the FGD output file. The one that gets created in your Trenchbroom Games Directory. Looking at that will often tell you what went wrong, or clue you in on it, where and what it fails to write.

Also, I don't know if you fixed it, but your Targetname and Target base classes do *not* go in the Base FGD Files array in your Door Systems FGD File. I highly recommend going through the tutorial again to see where you may have gone wrong, as the FGD system is verified working with all of its various classes.

**Comment by PPBoxHead** [comment]
yeah I fixed the Base FGD Files array thing, but stills giving me the error:
![image](https://github.com/QodotPlugin/Qodot/assets/89146265/f8418335-ef1e-4c2a-aebe-ccac2b49f987)
My FGD File after export looks like this:
```
@SolidClass color(204 204 204) base(Targetname) = door : "Door brush that opens and closes with a button or Player Input." [
    close_position(string) :  : "0 0 0"
    close_speed(float) :  : "1.5"
    is_interactable(integer) :  : 0
    key_index(choices) = [
        3 : "air_key"
        4 : "earth_key"
        1 : "fire_key"
        0 : "no_key"
        2 : "water_key"
    ]
    open_speed(float) :  : "1.5"
    start_closed(integer) :  : 1
    tween_trans_type(choices) = [
        10 : "TRANS_BACK"
        9 : "TRANS_BOUNCE"
        8 : "TRANS_CIRC"
        7 : "TRANS_CUBIC"
        6 : "TRANS_ELASTIC"
        5 : "TRANS_EXPO"
        0 : "TRANS_LINEAR"
        4 : "TRANS_QUAD"
        3 : "TRANS_QUART"
        2 : "TRANS_QUINT"
        1 : "TRANS_SINE"
        11 : "TRANS_SPRING"
    ]
]

@SolidClass color(204 204 204) base(Targetname, Target) = button : "Button Brush that can trigger a pressed signal." [
    callable_method(string) :  : ""
    global_signal_name(string) :  : ""
    key_index(choices) = [
        3 : "air_key"
        4 : "earth_key"
        1 : "fire_key"
        0 : "no_key"
        2 : "water_key"
    ]
    press_signal_delay(float) :  : "0"
    release_signal_delay(float) :  : "0"
]
@SolidClass = detail : "Detail Brush" [
]

@SolidClass = group : "Brush Group" [
]

@SolidClass = illusionary : "Non-colliding Brush" [
]

@SolidClass = trigger : "Trigger Volume" [
    target(string) :  : ""
]

@SolidClass = wall : "Basic entity brush." [
]

@SolidClass = worldspawn : "World Entity" [
]
@PointClass size(-8 -8 -8, 8 8 8) base(Targetname, Target) = receiver : "Calls methods on target." [
    receiver_name(string) :  : ""
]

@PointClass size(-8 -8 -8, 8 8 8) base(Targetname, Target) = signal : "Name of signal to call target." [
    signal_name(string) : "Name of signal to call on target." : ""
]
```

**Comment by RhapsodyInGeek** [comment]
Yeah, so you're not including the Targetname and Target base classes in your FGD entities array. That's why they don't show up. I would recommend redoing your QodotFGDFile resource from the beginning, to try to figure out where you went wrong. Remember that BaseClasses still need to be included in an FGD File the same exact way that PointClasses and SolidClasses need to be.

**Comment by PPBoxHead** [comment]
Yeah, I got it now, that was the main problem, I didn't had Targetname and Target in the FGD entities array of the main FGD File resource.
Thanks a lot for the help!
