### ISSUE TITLE
Non-Worldspawn brush entities build incorrect ConvexPolygon Shape vertices

### ISSUE THREAD

**Issue by knil79** [QodotPlugin/Qodot#13]
the convex collsisionPolygons that are created seems to have way to many points, and some of them are modified by inverse_scale_factor and some are don't
 
Making collision shapes look like this
![image](https://user-images.githubusercontent.com/18348392/219737292-0550aaf6-6d51-4855-9160-a0bea86b5cc8.png)

I think the problem is in Qodot.cs starting on row 222 FetchSurfaces
I suspecting that inverseScaleFactor is not being used properly and that it also might add the points to many times so that i get atleast the double amount of points (atleast it looks like to many points)

 this only showed up when i changed so that detail brushes was set so the are their own entitys
like this
![image](https://user-images.githubusercontent.com/18348392/219737935-026efecc-3527-4be5-8986-7315071624fd.png)

**the wierd thing is that the worldspawn entity convex polygon collisionshape shapes is fine!!** 

This the how i want the entities to look in the end with detail entities:
![image](https://user-images.githubusercontent.com/18348392/219738782-db7add27-c95c-4ed1-ac45-ca149b182662.png)

I run on an inverse scale factor of 13.

I will attach the map file i try to import:
[island_tile_start.zip](https://github.com/QodotPlugin/Qodot/files/10769632/island_tile_start.zip)

EDIT1:
After looking some more I can see that a box that is suppose to have 8 points in the convexpolygon has 24,  BUT if i take the 4 first values and the 4 last values the box shape is created properly! This only worked for a box that is suppose to have 8 points, other boxes was still wrong, will look into it

**Comment by bytes-ls** [comment]
Not sure if it's the same bug, but I have something similar happening.

Steps to reproduce:
 - Create map in trenchbroom with 3 brushes, group two of them together and set those two to clip texture
 - Hold ctrl and drag on grouped clip brushes, cloning them, then save
 - Open godot, generate map
 - Notice that the clipped brushes aren't in the right place anymore

Clicking on one of the collision shapes (a rectangle) reveals 24 points on the ConvexPolygonShape3D, but it should only be 8

Ungrouping them fixes the point count
Changing their textures to a non-special one fixes the placement, but not the point count

Hopefully this info will be helpful!

Thanks and great job

**Comment by DeerTears** [comment]
> Not sure if it's the same bug, but I have something similar happening.
> 
> Steps to reproduce:
> 
>     * Create map in trenchbroom with 3 brushes, group two of them together and set those two to clip texture
> 
>     * Hold ctrl and drag on grouped clip brushes, cloning them, then save
> 
>     * Open godot, generate map
> 
>     * Notice that the clipped brushes aren't in the right place anymore
> 
> 
> Clicking on one of the collision shapes (a rectangle) reveals 24 points on the ConvexPolygonShape3D, but it should only be 8
> 
> Ungrouping them fixes the point count Changing their textures to a non-special one fixes the placement, but not the point count
> 
> Hopefully this info will be helpful!
> 
> Thanks and great job

What bytes is describing seems to be a new issue for grouping? Clip textures may be a result of https://github.com/QodotPlugin/Qodot/issues/33 and doubled points may be a result of https://github.com/QodotPlugin/Qodot/issues/46 which is being fixed right now.

I'd love to know if this is still happening for your maps or if one of the above bugs might be the culprit in this. Thanks.

**Comment by knil79** [comment]
Would love to see this looked at! Without this fix I can't make new tiles for my game 😅

**Comment by EMBYRDEV** [comment]
> Would love to see this looked at! Without this fix I can't make new tiles for my game 😅

It's on our todo! You'll notice that we've been closing off a fair amoutn of issues lately including some geometry gen issues. When we get time we will address this. We haven't forgotten.

**Comment by knil79** [comment]
> 

VERY cool! Thank you! <3

**Comment by knil79** [comment]
> > Would love to see this looked at! Without this fix I can't make new tiles for my game 😅
> 
> It's on our todo! You'll notice that we've been closing off a fair amoutn of issues lately including some geometry gen issues. When we get time we will address this. We haven't forgotten.

VERY cool! Thank you! <3

**Comment by rburing** [comment]
Could someone please post clear reproduction instructions (or a scene and map file, or a project) for the original issue, i.e. the deformed colliders? Simply building the originally attached map doesn't reproduce it.

**Comment by rburing** [comment]
Commenting out this line seems to fix the original issue:

https://github.com/QodotPlugin/Qodot/blob/e76f4ac3464925c79286001701c3a6af21903aaa/addons/qodot/src/core/GeoGenerator.cs#L172

I'm not sure why this fixes it, or what's the proper fix.

**Comment by DeerTears** [comment]
Sorry this took so long! Thank you @rburing for pointing this out.

It seems like the brush vertices aren't totally set while the brush center is still being figured out. I'll admit I still don't understand the map parser code despite studying it today.

This line of code: `entity.center += brush.center; ` is made to set a brush entity's origin to the average of its vertex positions. It's so you can click on a brush entity from the 3D view and get a gizmo to appear at its origin, in case you wanted to move it around freely between builds. But it seems like this line is interfering with the vertex positions when generating Godot collisions. Mesh generation is safely done with libmap so it's not affected.

I've commented this line out and pushed a new commit: https://github.com/QodotPlugin/Qodot/commit/e9612739d72b21e7c9237bb713f9623418d1e083 I've tested this with some broken maps and found it works now. Unfortunately brush entities no longer have reasonable centers, so I'm hoping the next step can be to bring that back in a way that doesn't interfere with the vertex generation.

Thanks for your patience! And thanks for all the information!
