### ISSUE TITLE
Qodot Texture Loader uses "set_shader_param" instead of "set_shader_parameter"

### ISSUE THREAD

**Issue by blizzardlizard** [QodotPlugin/Qodot#134]
This is not a huge deal but I figure I would mention it nonetheless. When using a ShaderMaterial for Qodot's default material, I was getting an error and the textures would not load properly. After looking into it, this appears to be because in qodot_texture_loader, the following line:
`
material.shading_mode = BaseMaterial3D.SHADING_MODE_UNSHADED if unshaded else BaseMaterial3D.SHADING_MODE_PER_PIXEL
`
Does not check if the material HAS a shading mode to begin with, so it was creating errors with the shader I was using that did not have that variable. I was able to fix it by simply adding a line to check if the material has the shading mode variable before setting it 👍

**Comment by blizzardlizard** [comment]
Oops my bad, that is not the issue I was having and setting it to unshaded would have fixed it, however there WAS another problem which is that the function used to set the albedo texture:

> material.set_shader_param(default_material_albedo_uniform, texture)

was resulting in an invalid call error that said set_shader_param couldnt be found. I WAS able to fix THAT by changing it to set_shader_param_eter_ instead

**Comment by RhapsodyInGeek** [comment]
I could've sworn I fixed both of these exact bugs some time back.

**Comment by RhapsodyInGeek** [comment]
Both of these had been fixed some time ago and are in the current public code base and should be in the latest AssetLib version as well now.
https://github.com/QodotPlugin/Qodot/blob/main/addons/qodot/src/util/qodot_texture_loader.gd#L154

Make sure you keep your Qodot up to date. Remember that the GitHub version will always have the most up to date fixes in case you're having issues with the AssetLib version.

**Comment by blizzardlizard** [comment]
Ohhh okay, Thank you!
