### ISSUE TITLE
Wrong material textures

### ISSUE THREAD

**Issue by CachorroVoador** [QodotPlugin/Qodot#139]
For some reason, the materials used are changed when the game starts or when I restart the scene
I use the godot addon store version

https://github.com/QodotPlugin/Qodot/assets/87171245/d0674f4f-39f6-4cd4-9301-8bd5d2798b0d

**Comment by RhapsodyInGeek** [comment]
Once Qodot generates the meshes and applies the materials, it's done and no longer affects the map. It also will assign materials based upon the material name.

I've noticed that it only seems to be your light brown texture that's getting overridden. Did you manually assign the light brown material to that mesh after generation? Is there maybe a mix up with your materials somewhere in your project? Have you tried rebuilding the map?

Can you also share your map file? It might help illuminate some things to read it.

**Comment by CachorroVoador** [comment]
Good afternoon
So, I don't know if there is a mix. I've checked Trenchbroom countless times and tried deleting and recreating the texture again, but the same thing continues.
[garage_map.zip](https://github.com/QodotPlugin/Qodot/files/13846453/garage_map.zip)

**Comment by RhapsodyInGeek** [comment]
So the map file seems fine, checks out. Not too sure what's going on. I'd personally start by double checking the surface materials on your map scene's mesh resources, see if for some reason they've actually switched away from your light_brown material to gray or if the light_brown material is getting messed up.

**Comment by CachorroVoador** [comment]
I'm going to try to redo the texture materials to see if there isn't a bug on Godot's part or something like that.

**Comment by CachorroVoador** [comment]
It seems that having recreated the materials may have resolved
Strange, but it was resolved at least
