### ISSUE TITLE
Support for separate albedo texture in auto-pbr materials

### ISSUE THREAD

**Issue by mode777** [QodotPlugin/Qodot#150]
The [docs on auto pbr materials](https://qodotplugin.github.io/docs/materials.html#automatic-pbr-texturing) state:
> Tip: Since you can separate albedo from editor textures, it may help to add a grid or other distinguishing features of the material as a part of its editor texture, to aid in aligning the texture to neighbouring brushes.

I agree that this would be very helpful, in my case to keep a lower res texture for trenchbroom while using a higher res albedo in Godot. However, it is not apparent how to achieve this as pbr materials do not support a separate albedo texture channel (e.g. "*_albedo.*"). Am I missing something here?

It is trivially easy to add this support by modifiying the qodot sources but I'd like not to touch the plugin code to stay compatible for updates.

UPDATE: I'm open to do a PR if there is an agreement to add this support

**Comment by RhapsodyInGeek** [comment]
I think this support would be useful, but to maintain backwards compatibility with older versions you'll need to have the albedo fallback onto the representative texture.

There aren't any Qodot Team plans on adding it to Qodot (we're just looking at bug fixes at this point and active development has moved onto the new plugin), but if you can come up with a working implementation that follows the current design patterns while keeping the texture fallback so people don't have to change their work flows if they're already working with Auto-PBR, I think that'd be good.

**Comment by RhapsodyInGeek** [comment]
We're getting ready to release a successor to Qodot, under a new name. We haven't really given a proper announcement for it, but we've been discussing it a lot on the Discord.

**Comment by RhapsodyInGeek** [comment]
Resolved by #151
