### ISSUE TITLE
Textures not showning up in godot

### ISSUE THREAD

**Issue by niels1020** [QodotPlugin/Qodot#157]
When i import my map into godot and hit the full build button my aplied textures don't show up the right file extension is configured and the texture path points to my textures and i am gettin this error.
res://addons/qodot/src/nodes/qodot_map.gd:378 - Invalid call. Nonexistent function 'get_entity_definitions' in base 'Resource (QodotFGDFile)'.

**Comment by Jalkhov** [comment]
I have the same problem dude, how did you solve it?
