### ISSUE TITLE
Trying to build map gives FGD error

### ISSUE THREAD

**Issue by Creamsicle42** [QodotPlugin/Qodot#158]
When trying to build (or full build) a map after installing the Qodot plugin, I receive the error
```
res://addons/qodot/src/nodes/qodot_map.gd:378 - Invalid call. Nonexistent function 'get_entity_definitions' in base 'Resource (QodotFGDFile)'.
```
Alongside this, the level geometry is present, but there is no collision and no entities (IE, lights) have been properly instantiated.  Issue is occurring on the latest version of Qodot 4 from the asset library and Godot 4.2.1 mono

**Comment by zantze** [comment]
Seems as if Godot has changed the Resource API to not support function calls from scripts inheriting Resource type. 

I managed to fix it by changing all the functions in `godot_fdg_file.gd` to be static.

**Comment by zantze** [comment]
You can also try this: https://github.com/QodotPlugin/Qodot/issues/156#issuecomment-2050241018

**Comment by Creamsicle42** [comment]
The second solution worked perfectly, thank you!
