### ISSUE TITLE
Does the latest version actually require .NET?

### ISSUE THREAD

**Issue by toolness** [QodotPlugin/Qodot#160]
Hi!  I have a really basic question... I asked on Discord but haven't received a reply yet so I figured I'd ask here too (also, it might help folks who are browsing the repo and confused).

When I looked at this project about a year ago, it was .NET/C#-based... Today I visited this repository and there don't seem to be any `.cs` files in it at all, and the one mention of C# in the README is struck-through and replaced with "GDScript".  This made me think that perhaps the latest version is now vanilla GDScript.

However, when visiting the official docs, it claims I need to use the .NET version of Godot to use the plugin... so i am confused.  Does the latest version of Qodot require the .NET version?

**Comment by whussgit** [comment]
I checked on two engine versions (Standart/.NET) and everything works fine

**Comment by EMBYRDEV** [comment]
you no longer need .NET however this plugin has migrated to a new home! https://github.com/func-godot/func_godot_plugin
