### ISSUE TITLE
Unable To Load Plugin Script

### ISSUE THREAD

**Issue by Alpha-AC** [QodotPlugin/Qodot#18]
Hey!
Anyone know why I can't load the Qodot plugin in Godot 4? It's giving me this error.

![screenshot1](https://user-images.githubusercontent.com/99102966/222839196-753de871-2748-4ecc-9adc-39e8c743ff7d.png)
![screenshot2](https://user-images.githubusercontent.com/99102966/222839237-3ff262bb-3623-462c-b53c-712582e6fb21.png)

**Comment by DeerTears** [comment]
We recently just pushed #15 which addresses this. Godot hit us with a lot of quick changes at the last second to these new functions and the types of their arguments/return values. Try removing the /addons/qodot folder, download the plugin from github, and see if that doesn't fix things.

**Comment by Alpha-AC** [comment]
Alright, the plugin still wouldn't load at first because of this error in the code (i think there's a missing comma after TYPE_STRING?) :

![ss3](https://user-images.githubusercontent.com/99102966/222872450-41e049cf-f818-4bcc-888f-78f30b8586b4.png)

After that, the plugin loaded, but the option to build the TrenchBroom map would not appear in the toolbar.

**Comment by Alpha-AC** [comment]
Ahh, it looks like I have an outdated version of the .NET SDK as well. That could be part of the issue.

**Comment by DeerTears** [comment]
Aw jeez, the comma is a PR I just merged without testing since I wanted to move things along, thanks for catching that. 😅 Qodot_Map.gd might have errors that weren't caught which preventing the plugin options from being added.

**Comment by Alpha-AC** [comment]
Alright, thanks for your help anyways.

**Comment by knil79** [comment]
> Alright, thanks for your help anyways.

Fix for the comma is on master now

**Comment by DeerTears** [comment]
@Alpha-AC  Try downloading [.NET 7.0 latest](https://dotnet.microsoft.com/en-us/download) and opening your project again. Make sure you click "Build" in the top right of the Godot editor, then enable the plugin.
