### ISSUE TITLE
Plugin failing from outdated RC2 script: `QuakeWadImportPlugin.cs`

### ISSUE THREAD

**Issue by DeerTears** [QodotPlugin/Qodot#20]
Right now Qodot 4 does not work as intended on Godot 4.0 stable. This is because the WAD import plugin is failing on initialization, preventing the rest of the plugin from loading properly. Godot isn't flagging what is broken about the script, so I've been uncertain how to solve this. My main goal with this issue is to spread awareness that **the plugin on Github is broken currently, and a fix is coming soon.**

`QuakeWadImportPlugin.cs` is the script: https://github.com/QodotPlugin/Qodot/blob/main/addons/qodot/src/import_plugins/QuakeWadImportPlugin.cs the move from RC3 to Stable regressed the script and caused it to return `null` when initalized in `qodot_plugin.gd` and again in `qodot_map.gd`.

---

If you, a user, need to use the plugin right now, consider these three options:

> Backup your project, download [Godot 4.0 RC2](https://downloads.tuxfamily.org/godotengine/4.0/rc2/), and use Qodot in the Assetlib (yet to be updated as of writing)

> Use 4.0 stable, and comment out any references to WAD files in both qodot_plugin.gd and qodot_map.gd. Use loose textures instead. This worked for me in stable, but I didn't test it as thoroughly for exporting.

**or (ideally)**

> Help us fix the C# regressions from RC2 to Stable 🙏 

Anyone with basic C# experience, especially C# in Godot, I'd really appreciate getting your take on what needs fixing in this file to work with stable: https://github.com/QodotPlugin/Qodot/blob/main/addons/qodot/src/import_plugins/QuakeWadImportPlugin.cs

---

Related issues:

#19 Build button not showing because of this plugin failing

**Comment by EMBYRDEV** [comment]
This is a little strange, I've just done a fresh clone of Qodot and Godot 4.0 stable and things seem to be working fine... will have to check on my macbook later!

**Comment by ShadowFungi** [comment]
have you attempted changing line 36 in qodot_plugin.gd from
`	wad_import_plugin = load("res://addons/qodot/src/import_plugins/QuakeWadImportPlugin.cs").new()`
to 
`	wad_import_plugin = preload("res://addons/qodot/src/import_plugins/QuakeWadImportPlugin.cs").new()`?

I've only tested it on Linux thus far, but it seems to be working with that change.

**Comment by DeerTears** [comment]
After some digging Embyr found that the solution is to install .NET 7.0 latest, not 6.0 stable.
