### ISSUE TITLE
Document .NET 7.0 download requirement for Qodot

### ISSUE THREAD

**Issue by DeerTears** [QodotPlugin/Qodot#23]
# Setup
1. Have a Godot project with `res://addon/qodot` obtained from this repository for 4.0 stable support
2. [Download .NET 7.0 standard term support](https://dotnet.microsoft.com/en-us/download)
3. Project > C# > Create C# Solution
4. Click "Build" in the top right corner of the editor
5. Project > Project Settings > Plugins, then enable Qodot

Normally I put documentation issues here: https://github.com/QodotPlugin/qodotplugin.github.io/issues/ but this is to re-iterate that you need .NET 7.0 installed for the current iteration of the plugin downloadable from Github to work.

**Comment by RisingThumb** [comment]
I see .NET 7.0 is installable on Linux. Do you know if there's any reason why it wouldn't? Is it still cross-compatible?

**Comment by DeerTears** [comment]
Qodot (4.0) with .NET 7.0 installed should work regardless of OS, from my brief look through their issues there's none specifically regarding Godot's .NET compatibility with a particular OS.

Though as of 4.0.2. any exported (.exe, .app, etc.) Godot game that runs a C# script still pushes errors, and may crash. That is still out of our hands until it's fixed. https://github.com/QodotPlugin/Qodot/issues/22

**Comment by DeerTears** [comment]
I'd say I've sufficiently warned people in most of the places possible about the .NET requirement now.
