### ISSUE TITLE
qodot_trenchbroom_config_folder.tres won't open because of non-existent svg icon in plugin folder

### ISSUE THREAD

**Issue by cybernaut4** [QodotPlugin/Qodot#25]
# Problem
Godot won't open the `qodot_trenchbroom_config_folder.tres` file. 
> File is located here: `res://addons/qodot/game_definitions/trenchbroom/qodot_trenchbroom_config_folder.tres`

## Reason
`qodot_trenchbroom_config_folder.tres` is trying to load a non-existent svg icon @ line 4
```
[ext_resource type="Texture2D" uid="uid://b2k2iutnsgjfy" path="res://addons/qodot/icon.svg" id="2"]
```
## Fix choices
A. Edit the filepath to point to the existing "icon.**png**" instead
B. Upload an icon.svg and remove icon.png

**Comment by DeerTears** [comment]
Closed by https://github.com/QodotPlugin/Qodot/commit/2565dadf4aca8b029bc67cbdfdf15ffb149a017a
