### ISSUE TITLE
Example scenes missing old descriptions

### ISSUE THREAD

**Issue by GelosoFederico** [QodotPlugin/Qodot#29]
Hi! I wanted to start using qodot with the release of godot 4, and I was a bit lost with the readmes for the example scenes. Turns out that those disappeared with the migration from godot 3 to 4. 

Do you mind me opening a PR adding those as editor descriptions? That field in godot scenes changed from 
```
__meta__ = {
"_editor_description_": ""
}
```

in godot 3 to just "editor_description" in godot 4

**Comment by DeerTears** [comment]
Yeah go ahead! I will admit the example scenes themselves are ancient, but still prove as an okay testbed for seeing the plugin in action. In the meantime though this seems like only a good thing.

**Comment by GelosoFederico** [comment]
PR Open https://github.com/QodotPlugin/Qodot/pull/30

Yeah, I figured they were not a very viable way to learn but seeing the maps in action is at least a way to check if some parts are installed correctly.
