### ISSUE TITLE
Build every model object as separate mesh

### ISSUE THREAD

**Issue by jairbolsonaropresidenteem2026** [QodotPlugin/Qodot#32]
Hello! How are you?

My question is: Is there any way to compare the map, but instead of merging everything into a single model, does it create a mesh instance for each object on the map? I think it would be better to use occlusion occluder and etc.

Example:
![image](https://user-images.githubusercontent.com/129339356/228683620-a3cf4a59-1a45-4e9f-b501-02936bb8cccb.png)
![image](https://user-images.githubusercontent.com/129339356/228683789-038c0e76-9499-44e7-8646-00e65694fe61.png)

Instead of merging all these cubes into a single mesh instance, it creates multiple nodes for each cube.

**Comment by EMBYRDEV** [comment]
if you group brushes together in trenchboom using `func_group` then these will be built as separate meshes. You can also define how each entity type is merged or not in the Entity Fgd file by changing it's "Spawn Type".

<img width="553" alt="image" src="https://user-images.githubusercontent.com/20043270/230797448-5ce5b508-cd6d-4b58-8748-5d3f64003630.png">
