### ISSUE TITLE
Change collision layer/mask on worldspawn's StaticBody3D from QodotMap's properties - feature request

### ISSUE THREAD

**Issue by cybernaut4** [QodotPlugin/Qodot#38]
# Problem

It's not possible to configure QodotMap node to build with predefined set of collision layers.

It has to be selected after every time the map is built. Since it's a special scenario, this extra step could be easy to forget after a while.

### Example

The pickup objects need to bounce with the world as they're dropped by enemies and, if player moves too fast towards them, they can interrupt player's momentum. Therefore two layers are used:

Layer 1 is **default**.
Layer 2 is **pickableObjects**.

"Player" is a CharacterBody3D inside **default** layer.
"PickableArea" is an Area3D, child of Player, and only scans the **pickableObjects** layer.
 
Worldspawn is set with **default** & **pickableObjects** layers.

## Potential solution

Add a collision layer and collision mask grid within QodotMap node's properties to adjust Worldspawn layers.

**Comment by EMBYRDEV** [comment]
Good idea! Will look into adding this feature.

**Comment by RhapsodyInGeek** [comment]
So looking into it, I don't think the answer would be to set it as a property of the QodotMap node. Worldspawn is just another Solid Class entity, and the only actually unique thing about it seems to be that it always has its origin set to `0 0 0`. If worldspawn is undefined in the FGD resource then it defaults to standard QodotEntity generation behavior.

Instead I think we should add it as an option to the **QodotFGDSolidClass** resource, just like we already have _Collision Type_ as an option on it. Then, if a user needs to have _any_ SolidClass collision layer or mask changed they can do so on a per entity class basis.

It should be a pretty easy addition, too. Would probably only need to modify the SolidClass resource script and qodot_map.gd.

**Comment by DeerTears** [comment]
Closed by #97
