### ISSUE TITLE
Remove "almost-duplicate" points when building the shape for Godot Physics

### ISSUE THREAD

**Issue by Gamepro5** [QodotPlugin/Qodot#46]
Building a map using Qodot can sometimes mess up the collision detection for godot physics if trenchbroom decides to have vertices at very similar locations.

Diagnosis of the issue: https://github.com/godotengine/godot/issues/78066#issuecomment-1585603013

(MRP from that issue was generated using [this map](https://github.com/QodotPlugin/Qodot/files/11713466/map.zip) using Qodot 2.1.0).

**Comment by EMBYRDEV** [comment]
does this issue go away if you raise `CMP_EPSILON` in GeoGenerator.cs?

**Comment by Gamepro5** [comment]
No, it does not. I tried 0.018 and it still doesn't fix it.

**Comment by rburing** [comment]
From a glance (take it with a grain of salt) it seems Qodot 4 generates `Vector3` vertices per face, and it keeps all of them (hence duplicates and near-duplicates everywhere that faces touch) in the collision shape. It would be more efficient (for both the mesh and the collision shape) to generate a list of vertices *per brush* (filtering duplicates and merging near-duplicates), and to define faces using `int` indices into the vertex list.
