### ISSUE TITLE
Update plugin.cfg version string

### ISSUE THREAD

**Issue by DukeVengeance** [QodotPlugin/Qodot#48]
This is the string that will be shown in the Godot Plugin window, and it hasn't been changed since porting to 4.x.

https://github.com/QodotPlugin/Qodot/blob/4f6f604331025ecf1fdd5ac2091db33b8a815b86/addons/qodot/plugin.cfg#LL6C27-L6C27

**Comment by DeerTears** [comment]
Done! Thanks for the reminder, I'll do this for the github release too.
