### ISSUE TITLE
Load the .map using relative path (res://)

### ISSUE THREAD

**Issue by cybernaut4** [QodotPlugin/Qodot#58]
# Situation

Opening Qodot's example scenes and attempting to build.

# Problem

QodotMap targets the .map file with an absolute path, making tedious to showcase examples or even load Qodot projects from other computers.

Example: `P:\computer\projects\gamedev\game\addons\example_scenes\0-visuals\0-structural-geometry\0-structural-geometry.map`. 
This affects even personal projects when working from a different computer setup.

# Solution

The **Map File** field in the inspector could use Godot's relative path to locate it (`res://`)

Example: `res://addons/example_scenes/0-visuals/0-structural-geometry\0-structural-geometry.map`.

**Comment by DeerTears** [comment]
Ah, this choice for me has been deliberate, as I often build maps from outside of my project before moving them into the project and committing them. This way it skips a little bit of import lag on alt + tab, and I use this regularly to test people's maps as a developer. But I recognize this isn't the most convenient or surefire way to keep your project files together.

Would other people find a switch from global directory to project directory useful?

I could look into trying to change the directory scope with project settings, using `_set()` and `_get_property_list()`, but it seems fairly undocumented in the examples territory so it might take some time.

**Comment by cybernaut4** [comment]
> Ah, this choice for me has been deliberate, as I often build maps from outside of my project before moving them into the project and committing them. This way it skips a little bit of import lag on alt + tab, and I use this regularly to test people's maps as a developer. But I recognize this isn't the most convenient or surefire way to keep your project files together.
> 
> Would other people find a switch from global directory to project directory useful?

Understandable. Then maybe a more flexible solution? what about adding a boolean property in the inspector like "Use Absolute Path"? 
* If true, it would use OS' way to target a file (eg. `D:\Documents\GodotProjects\MyGame\My.map` or `~/Documents/Projects/Game`).
* If false, it'd use the `res://` prefix instead.

That way it's possible to eg. build the map before including it in the project, then create a backup altogether.

**Comment by mrdaemon** [comment]
I would also love if the maps could be referenced relatively, as they're part of the source tree and assets, and becomes tedious quickly to change all the paths when doing a vcs checkout from another system.

**Comment by mrdaemon** [comment]
As a bonus I just discovered that apparently if you feed the inspector field on a QodotMap node with a resource path manually, i.e. `res://maps/my_glorious_brushwork.map` -- it appears to load, build and work fine without depending on filesystem layout.

This works for me as I don't bind those elements all that often, and it makes the project portable, while retaining the ability to load arbitrary maps from filesystem.

I'm just laving this information here in case someone else wanders in looking for A Workaround(tm)

**Comment by Nikoraito** [comment]
I prefer relative. Perhaps the default behavior could be absolute if outside of the project and relative if inside it? One argument for me in favor of relative is that my team and I share a codebase live via a synced folder, so if one of us picks an absolute path, that path is broken for everyone else. As noted above, however, using `res://` works fine as long as we remember to change it manually.

**Comment by mrdaemon** [comment]
It turns out also, if you drag and drop the map file onto the field via the godot filesystem browser, it genrates a `res://...` path on its own, which may also help in reducing friction involved in attaching it in a way that doesn't break through VCS.

**Comment by RhapsodyInGeek** [comment]
Closing this issue. While there are no plans to add this functionality to the current version of Qodot as it is a breaking change and easy workarounds have been shared, the option to use either local or global paths has been added to the upcoming successor plugin's features.
