### ISSUE TITLE
Can't save in Trenchbroom after a "Full Build" in Godot 4.1

### ISSUE THREAD

**Issue by alsomedud33** [QodotPlugin/Qodot#61]
Since updating Godot from Godot 4.0.3 to Godot 4.1. Whenever I do a "full build" in Godot of my Trenchbroom map, then i go back to trenchbroom to make changes, I'm unable to save.

Trenchbroom comes up saying, "Cannot open file: [Directory to Map"]
![image](https://github.com/QodotPlugin/Qodot/assets/59976168/de8de1fa-3b55-476f-9934-e6523d2d3a67)

For me to save in Trenchbroom again, I need to go back in Godot, reload the project, then I'm able to save again. But if I do a full build, Trenchbroom stops saving again.

**Edit:**
After looking at issue: (https://github.com/QodotPlugin/Qodot/issues/53#issue-1773327673)

I've managed to fix the issue by going to the Qodot addon > src > core > MapParser.cs:
![image](https://github.com/QodotPlugin/Qodot/assets/59976168/54570f53-cbfc-4761-89d9-57753ecbc80a)

Then on line 80 of the Script, I added `file.Close();`
![image](https://github.com/QodotPlugin/Qodot/assets/59976168/0e8397e8-ecf4-4b29-8411-edbc85ded5f2)

Now the Problem is fixed!

**Comment by RealPlanet** [comment]
I've opened a PR for this, on my end it seems to be working. Feel free to try it out on yours

**Comment by EMBYRDEV** [comment]
Closed by https://github.com/QodotPlugin/Qodot/pull/62#event-9767532667 Thank you @RealPlanet.
