### ISSUE TITLE
Separate Meshes for Each Brush

### ISSUE THREAD

**Issue by humansandbag** [QodotPlugin/Qodot#67]
This plugin creates a single Array Mesh for the entire map. In old BSP game engines, you could hit individual brushes with a raycast for doing various things like getting the texture name for that specific brush. Please change it so that Build Meshes creates separate meshes and collision shapes for each brush.

**Comment by humansandbag** [comment]
I like the idea of separate bodies by material. That would be ideal. Thanks for the tip on grouping them. I have a similar workaround I've been using, but having to do so impacts productivity.

**Comment by RhapsodyInGeek** [comment]
Closing as discussion is old, user found own solution, and the original proposal was already implemented with the way Qodot handles brush entities.
