### ISSUE TITLE
Newest godot (4.1.something) plugin doesn't work

### ISSUE THREAD

**Issue by NurdAlert** [QodotPlugin/Qodot#68]
res://addons/qodot/src/qodot_plugin.gd:41 - Invalid call. Nonexistent function 'new' in base 'CSharpScript'.

Godot Engine v4.1.1.stable.mono.official (c) 2007-present Juan Linietsky, Ariel Manzur & Godot Contributors. <-- my godot version

fix asap 🙏

**Comment by steezeburger** [comment]
I had this same issue, and followed the directions in the setup exactly. 

I think the ordering may be wrong. I had to do the build process again after enabling the plugin, and then close and reopen godot, then I got past this error.

**Comment by EMBYRDEV** [comment]
> I had this same issue, and followed the directions in the setup exactly.
> 
> I think the ordering may be wrong. I had to do the build process again after enabling the plugin, and then close and reopen godot, then I got past this error.

Yeah it's quite annoying, I don't think there is a whole lot we can do about how godot inits c# plugins D:

**Comment by DeerTears** [comment]
Mhm, hate to say it but restarting the engine does sometimes just fix things. I'll add an optional step to restart in the readme, since it seems Godot versions are coming out a lot faster these days and we don't know what'll be required.
