### ISSUE TITLE
Qodot takes TrenchBroom's layers like func_groups. Any entities inside aren't included as children.

### ISSUE THREAD

**Issue by cybernaut4** [QodotPlugin/Qodot#69]
# Situation

I'm developing a top-down shooter with multiple layers of height as goal.

Layers in TrenchBroom can be used to encapsulate geometry and entities. This way, from Godot I could hide and disable crosshair collisions if Player isn't on said floor.

# Problem

* Qodot seems to parse the extra Layers saved in TrenchBroom's .map as ordinary func_groups.
* Every entity inside the layer is treated by Qodot as a sibling node, denying the idea of in-depth level design complexity.

**Note** that this feature could've been used for **modular loading**, also useful for **First Person Perspective**, allowing to keep "the whole picture" in one big map (eg. seamless loading).

# Minimal Reproduction Project
[QodotLayersFail.zip](https://github.com/QodotPlugin/Qodot/files/12135741/QodotLayersFail.zip)

(Once open, place your cursor on the QodotMap node for details.)

**Comment by cybernaut4** [comment]
# Minimal Reproduction Project
[QodotLayersFail.zip](https://github.com/QodotPlugin/Qodot/files/12135741/QodotLayersFail.zip)

**Comment by DeerTears** [comment]
This sounds reasonable! Making layer hierarchy match Godot's scenetree hiearchy sounds great. This current behaviour might actually have been a mistake during conversion from 3.x to 4.x. Thanks for noting this, and thanks for the example project.

**Comment by RhapsodyInGeek** [comment]
There wasn't anything about layers IIRC from my studying of both Qodot 3.x and Qodot 4.x. It was SpawnType.GROUP that was supposed to create a tree hierarchy if `Use Trenchbroom Group Hiearchy` was enabled on the QodotMap. One of my goals is to study it more to make sure it in fact is broken and to see if I can fix it.

That said, it might be useful to have a `Use Layers Hierarchy` toggle and add this as a feature.

**Comment by RhapsodyInGeek** [comment]
Trenchbroom Group Hierarchy resolved with #137
