### ISSUE TITLE
No full build/UnwrapUV2/Quick Build buttons.

### ISSUE THREAD

**Issue by marganec** [QodotPlugin/Qodot#70]
I've created a small test map in Trenchbroom just to look how it will look in Godot. But...
There is no this three buttons:
![изображение](https://github.com/QodotPlugin/Qodot/assets/89912214/acf95dce-d93c-4efb-87a1-dac63a6ed38b)
This is how it looks in my Godot project:
![изображение](https://github.com/QodotPlugin/Qodot/assets/89912214/4d4ae67e-b828-4b13-9370-3a1b85ccc3ac)
??????

**Comment by EMBYRDEV** [comment]
![image](https://github.com/QodotPlugin/Qodot/assets/20043270/c2c13760-466d-4dfd-867c-0e8d7b1551dd)

At the top of the README. 

You're using the non -mono engine build.
