### ISSUE TITLE
Build brushes with "skip" as Concave shapes

### ISSUE THREAD

**Issue by DeerTears** [QodotPlugin/Qodot#72]
# Current Behaviour

Currently, skip and clip function the same. They remove faces from geometry, and retain the brush's convex shape when built as collision. This makes sense as all brushes are convex shapes in Quake and Trenchbroom. We build these as convex Godot shapes for performance and simplicity. The best reason we have for keeping both options is to extend compatibility with original Quake maps.

However, the current behaviour is confusing for some users who have explained their need for collisions to not be applied to certain faces of their brushes, similar to Quake's skip.

# Desired behaviour 

Putting skip on a brush face would let users pass through convex hulls if there is no geometry to suggest it, while allowing the visible inside faces to retain collision.

ConcavePolygonShape3D has the ability to satisfy this desired behaviour. Taken from its docs page:

> Being just a collection of interconnected triangles, `ConcavePolygonShape3D` is the most freely configurable single 3D shape. It can be used to form polyhedra of any nature, or even shapes that don't enclose a volume. However, `ConvexPolygonShape3D` is hollow even if the interconnected triangles do enclose a volume, which often makes it unsuitable for physics or detection.

# Implementation

My idea is to separate brushes with `skip` to be their own `Arraymesh`. We can run `create_trimesh_shape()` on each to get a `ConcavePolygonShape3D`, and apply that to a new `CollisionShape3D` node. We could discard this `Arraymesh` and rebuild the brush's geometry back into the main mesh (or whatever else we want to implement for splitting geometry) to maintain the same graphics performance.

> ● void set_faces(faces: PackedVector3Array)
> 
> Sets the faces of the trimesh shape from an array of vertices. The faces array should be composed of triples such that each triple of vertices defines a triangle.

# Complications

> ● bool backface_collision [default: false]set_backface_collision_enabled(value) setteris_backface_collision_enabled() getter
>
> If set to true, collisions occur on both sides of the concave shape faces. Otherwise they occur only along the face normals.

I figure a face normal will always resort to the original convex shape that we generate, so we could reliably use this to force one-way collisions and allow users to jump through the backside of level geometry. This is a bit esoteric, and as Godot points out, really unreliable compared to just using convex shapes.

> Warning: Physics bodies that are small have a chance to clip through this shape when moving fast. This happens because on one frame, the physics body may be on the "outside" of the shape, and on the next frame it may be "inside" it. ConcavePolygonShape3D is hollow, so it won't detect a collision.

> Performance: Due to its complexity, ConcavePolygonShape3D is the slowest 3D collision shape to check collisions against. Its use should generally be limited to level geometry. For convex geometry, ConvexPolygonShape3D should be used. For dynamic physics bodies that need concave collision, several ConvexPolygonShape3Ds can be used to represent its collision by using convex decomposition; see ConvexPolygonShape3D's documentation for instructions.

# Additional Notes

This all assumes current bugs with skip/clip are addressed, such as #33 .

**Comment by RhapsodyInGeek** [comment]
So I thought of a simpler solution that should only require small modifications to Qodot.cs and SurfaceGatherer.cs.

A quick correction on Skip and Clip: they work slightly differently, with the net result being the same. Skip is can be applied to individual faces, whereas Clip must cover an entire Brush to be removed. If a Clip covers any less than every face on the Brush it will not remove any faces. It matches Quake behavior, but I still don't feel that justifies the difference in a Godot workflow.

Worldspawn is currently just treated as a SolidEntity with CollisionShapeType set to Convex, but it can easily be switched to Concave if the user prefers it. I think the built-in worldspawn should remain defaulted to Convex, but we should provide better tutorials on how it all works so users know they can change it if they wish.

### Implementation
Skip and Clip should both be checked in [SurfaceGatherer's FilterFace](https://github.com/QodotPlugin/Qodot/blob/main/addons/qodot/src/core/SurfaceGatherer.cs#L146) method during [Qodot's mesh generation](https://github.com/QodotPlugin/Qodot/blob/main/addons/qodot/src/core/Qodot.cs#L174). Then, during the [Qodot's concave collision generation](https://github.com/QodotPlugin/Qodot/blob/main/addons/qodot/src/core/Qodot.cs#L212) we should filter out the Skip Face again, but not during convex collision generation. Theoretically, this should allow skipping the Skip face collision generation while maintaining the Clip face collision. This also means we can avoid a post-build `create_trimesh_shape()` hack, only needing to go through the build process once as it currently works. It also takes advantage of the same face removal as the mesh generation does, which means it should build the collision you expect.

### Proposed Behavior Change
**Current Behavior**
- _Clip_ removes faces only when the entire brush is textured with _Clip_
- _Skip_ removes each face textured with _Skip_ regardless of brush coverage
- Collision is maintained regardless of _Clip_ or _Skip_ texturing

** Proposed Behavior**
- Both _Clip_ and _Skip_ remove each face regardless of brush coverage
- Collision is maintained regardless of _Clip_ texturing
- Convex collision maintains collision regardless of _Skip_ texturing
- Concave collision removes collision faces if textured with _Skip_

I think I'll try to whip up some experiments today, but I hope this proposal sounds good? It maintains the current exposed QodotMap node setup, keeps it simple, but adds a lot of flexibility under the hood.

**Comment by RhapsodyInGeek** [comment]
Examples of behavior:
![image](https://github.com/QodotPlugin/Qodot/assets/44485952/4fab5345-52a5-4eb0-b635-37b08b6065f3)
![image](https://github.com/QodotPlugin/Qodot/assets/44485952/a2534f12-f3d3-4f67-93bb-83b283920695)
You'll notice in the Godot screenshot there is no collision face where the Skip face was.

**Comment by RhapsodyInGeek** [comment]
We can probably close this issue as Resolved by #90.
