### ISSUE TITLE
Qodot exports game config icon name wrong

### ISSUE THREAD

**Issue by gulagkulak** [QodotPlugin/Qodot#89]
In [`trenchbroom_game_config.gd`](https://github.com/QodotPlugin/Qodot/blob/main/addons/qodot/src/resources/game-definitions/trenchbroom_game_config.gd) on line 57 Qodot defines the icon as "Icon.png" but writes it to disk as "icon.png" when exporting the game definition from Godot, causing Trenchbroom to not display the game icon in game definitions.

Fix: change "Icon.png" to "icon.png" on that line. Don't forget to rebuild for the code change to take effect.

I changed it in my copy of Qodot and it works fine now.

**Comment by DeerTears** [comment]
Thanks! Resolved by https://github.com/QodotPlugin/Qodot/commit/63e07c24c8150d89c9a4580676b35c6cd5ccf279
