### ISSUE TITLE
Toolbar buttons are missing

### ISSUE THREAD

**Issue by ruslanlezhnin** [QodotPlugin/Qodot#96]
- Godot v4.1.1 NET
- Qodot 4 v2023.2

Also when opening the project the following message is printed to console:
`res://addons/qodot/src/qodot_plugin.gd:41 - Invalid call. Nonexistent function 'new' in base 'CSharpScript'.`

**Comment by EMBYRDEV** [comment]
Did you follow all the steps in the readme, 90% of the time this error is due to a missed step,

**Comment by ruslanlezhnin** [comment]
You absolutely right. 

**My problem was that I didn't install the .NET 7 SDK**
After I did it and recreated c# solution, everything worked.
