### ISSUE TITLE
Problems with generating a GameConfig from Godot to Trenchbroom

### ISSUE THREAD

**Issue by Lassii-** [QodotPlugin/Qodot#99]
Hello,

I've been doing some initial testing with Qodot (great project btw!) and TrenchBroom and it's been working fine otherwise but I haven't been able to create a working GameConfig for my project to have a separate game entry in TB. My setup is Godot Mono 4.1.2 and TrenchBroom 2023.1 on Linux.

Exporting from Godot with trenchbroom_game_config.tres "Trenchbroom Games Folder" set to "/home/myuser/.TrenchBroom/games" and then opening TrenchBroom results in the following error:

![tb_error](https://github.com/QodotPlugin/Qodot/assets/8556790/5e4349fa-1c2b-434f-8846-d5f6b3d82d2a)

The contents of the generated GameConfig.cfg:
```
{
	version: 3,
	name: "QodotTesting",
	icon: "Icon.png",
	"fileformats": [
		{ "format": "Standard", "initialmap": "initial_standard.map" },
		{ "format": "Valve", "initialmap": "initial_valve.map" },
		{ "format": "Quake2", "initialmap": "initial_quake2.map" },
		{ "format": "Quake3" },
		{ "format": "Quake3 (legacy)" },
		{ "format": "Hexen2" },
		{ "format": "Daikatana" }
	],
	"filesystem": {
		"searchpath": ".",
		"packageformat": { "extension": "pak", "format": "idpak" }
	},
	"textures": {
		"package": { "type": "directory", "root": "textures" },
		"format": { "extensions": ["bmp", "exr", "hdr", "jpeg", "jpg", "png", "tga", "webp"], "format": "image" },
		"attribute": "_tb_textures"
	},
	"entities": {
		"definitions": [ "QodotEssentials.fgd", "QodotQuakeCompat.fgd", "QodotRecieverSignal.fgd", "QodotDemoEntities.fgd" ],
		"defaultcolor": "0.6 0.6 0.6 1.0",
		"modelformats": [ "mdl", "md2", "md3", "bsp", "dkm" ]
	},
	"tags": {
		"brush": [
			{
				"name": "Detail",
				"attribs": [  ],
				"match": "classname",
				"pattern": "detail*"
			},{
				"name": "Trigger",
				"attribs": [ "transparent" ],
				"match": "classname",
				"pattern": "trigger*",
				"texture": "trigger"
			}
		],
		"brushface": [
			{
				"name": "Clip",
				"attribs": [ "transparent" ],
				"match": "texture",
				"pattern": "clip"
			},{
				"name": "Skip",
				"attribs": [ "transparent" ],
				"match": "texture",
				"pattern": "skip"
			}
		]
	},
	"faceattribs": {
		"surfaceflags": [
			
		],
		"contentflags": [
			
		]
	}
}
```

So I'm not sure if I'm doing something wrong (or if I missed a step in the documentation; sorry if it's so!) or if there's something wrong elsewhere. The README said that Qodot documentation is undergoing maintenance so I figured I'll ask directly.

Thank you for any advice,
Lassi

**Comment by RhapsodyInGeek** [comment]
Looking at your error, it's obvious what it has a problem with. In this case it wouldn't be anything you're doing wrong... it's hardcoded that the version number is 3 in the GameConfig generation.

I'm not currently sure how best to solve it as I'm not sure there are more differences between different GameConfig versions, but you can try changing `version: 3` to `version: 7` in your GameConfig. I don't have Linux so I can't really test this, but I'd be interested to know if it works.

**Comment by RhapsodyInGeek** [comment]
@Lassii- did you ever figure out a resolution to this issue?

**Comment by Lassii-** [comment]
Sorry for late reply, been busy with other stuff. I actually tried switching the version before but forgot to mention that in the post. When I change the version to 7 (or 8), I get the following error.

![image](https://github.com/QodotPlugin/Qodot/assets/8556790/a1b3801a-3fb2-48d7-a3d7-c82268c40fb7)

**Comment by RhapsodyInGeek** [comment]
Okay, so it actually has a different format. I'll have to look into this more later, seems very weird and is the first I've heard of this. I also don't use Linux though, so it might be tough for me to debug.

**Comment by BlainMaguire** [comment]
I was experiencing the same issue with TrenchBroom on Linux with Qodot.

I had a look at the config in other games that worked for me with the editor (like Quake 2). Then in Qodot's GameConfig.cfg I updated ```version: 8``` on line 2 and replaced  line 19 from:
```"package": { "type": "directory", "root": "textures" },```
to:
```        "root": "textures",```
To get past the error and get into the editor. I was able to import a very simple map into Godot 4.

**Comment by Lassii-** [comment]
> I was experiencing the same issue with TrenchBroom on Linux with Qodot.
> 
> I had a look at the config in other games that worked for me with the editor (like Quake 2). Then in Qodot's GameConfig.cfg I updated `version: 8` on line 2 and replaced line 19 from: `"package": { "type": "directory", "root": "textures" },` to: ` "root": "textures",` To get past the error and get into the editor. I was able to import a very simple map into Godot 4.

I can confirm that this works for me too. Thank you for the solution!

**Comment by RhapsodyInGeek** [comment]
We should probably look at updating the TrenchbroomGameConfig resource to allow optional versioning so that Linux users don't have to manually do this. I'd need to study up on GameConfig version differences though to come up with a viable solution, and I don't really have the time right now unfortunately.

**Comment by RhapsodyInGeek** [comment]
Yeah, I mean it's not happening on the Windows versions, but I didn't think the official releases were that different. Seems the GameConfig exporter will need an update when the new version of TrenchBroom gets pushed to all platforms.

**Comment by EMBYRDEV** [comment]
Note to self, this was the breaking commit in TB https://github.com/TrenchBroom/TrenchBroom/commit/15be6de9a86ed9ec9dbee22dd2bdfbcb3a2bd076

It will be super easy to patch Qodot to support this new version of TB but currently the latest official release (March) doesnt include this commit (April) so any linux users facing issues are using packages that are more up to date than the official release.

**Comment by RhapsodyInGeek** [comment]
Think it'd be worth having a version toggle on the TrenchbroomGameConfig resource, and always default it to the latest official TB version? To stay safe for backwards compat? Probably wouldn't be that tough to implement but I'm wondering if we should concern ourselves with it or just only support the latest official release?

**Comment by Lassii-** [comment]
I just realized that I had a git build installed when I reported this bug and not the official 2023.1 release. I tried with the official release and it does indeed work without any changes. Sorry for the mess up!

**Comment by RhapsodyInGeek** [comment]
Closing this issue since it only occurs with unofficial advanced builds of Trenchbroom and does not affect the current official release. When Trenchbroom updates the GameConfig we will update Qodot to support the new version.

**Comment by lexical-lushes** [comment]
I just ran into this same problem on Windows while trying out TrenchBroom (version 2024.1) and Qodot (installed from the AssetLib for Godot 4.2.1-stable x64) for the first time. The GameConfig.cfg file created by using the trenchbroom_game_config.tres file in Godot looks very different in a few places to the ones inside TrenchBroom's other game folders and throws the same "configuration version 3, valid versions 7, 8" error as the OP.

I'm not confident enough to manually edit the GameConfig.cfg file without knowing what I'm doing, so this means that I cannot use Qodot at all currently.

**Comment by RhapsodyInGeek** [comment]
Download the source from the Github repository. It's up to date and works with Version 8. The Asset Lib version is extremely out of date, with no ETA on when it'll be updated.

**Comment by jonathanlake** [comment]
Having the same issue on Windows.

```
_TrenchBroom: An error occured while loading the game configuration files:

Could not load game configuration file FirstPersonMelee\GameConfig.cfg: At
line 2, column 13: Unsupported game configuration version 8; valid version are: 
3, 4_
```

If I change the version in the GameConfig.cfg from 8 to 3, I get a different error:

```
_TrenchBroom: An error occured while loading the game configuration files:

Could not load game configuration file FirstPersonMelee\GameConfig.cfg: At
line 15, column 14: Expected map entry 'format'
```


Godot version = 4.2.1.stable.official [b09f793f5]
TrenchBroom version = 2022.1
Qodot version = latest

**EDIT:** I may have fixed this by updating to the latest version of TrenchBroom.
